#define BOOST_TEST_MODULE cpp17 test
#include <boost/test/included/unit_test.hpp>
#include <unordered_map>

#include "test_util.h"

BOOST_AUTO_TEST_SUITE(test_linked_list_leetcode)

// "Find the Difference" problem (LeetCode #389)
// Problem:
// - You are given two strings s and t.
// - String t is generated by random shuffling string s and then add one more letter at a random position.
// - Return the letter that was added to t.
// Input: s = "abcd", t = "abcde"
// Output: "e"

BOOST_AUTO_TEST_SUITE(find_the_difference_suite)

char findTheDifference(std::string s, std::string t) {
	std::unordered_map<char, int> chars;
	for (char c : s) {
		++chars[c];
	}
	for (char c : t) {
		--chars[c];
		if (chars[c] < 0) {
			return c;
		}
	}
	return ' ';
}

BOOST_AUTO_TEST_CASE(find_the_difference_test) {
	TEST_MARKER();

	{ // Test 1
		std::string s = "abcd";
		std::string t = "abcde";
		std::cout << s << "\n";
		std::cout << t << "\n";
		char res = findTheDifference(s, t);
		std::cout << res << "\n\n";
	}

	{ // Test 2
		std::string s = "abcdefghij";
		std::string t = "hbedcfaijgk";
		std::cout << s << "\n";
		std::cout << t << "\n";
		char res = findTheDifference(s, t);
		std::cout << res << "\n\n";
	}

	{ // Test 3
		std::string s = "aaaaaaa";
		std::string t = "aaaaaaaa";
		std::cout << s << "\n";
		std::cout << t << "\n";
		char res = findTheDifference(s, t);
		std::cout << res << "\n\n";
	}

	{ // Test 43
		std::string s = "";
		std::string t = "a";
		std::cout << s << "\n";
		std::cout << t << "\n";
		char res = findTheDifference(s, t);
		std::cout << res << "\n\n";
	}
}

BOOST_AUTO_TEST_SUITE_END()

BOOST_AUTO_TEST_SUITE_END()